### ISSUE TITLE
Support to build combinators for YAML? 

### ISSUE THREAD

**Issue by seivan** [behrang/SwiftParsec#4]
So you closed this earlier.
https://github.com/behrang/SwiftParsec/issues/3
But then you mention in https://github.com/behrang/YamlSwift/issues/40#issuecomment-251642745 that you're planning on improving this to reimplement your YAML parser.

But for that, you'd need to support Indentation, from what I understand the regular implementation of Parsec (as in the one from Haskell ) doesn't exactly support this out of the box. 

I am still learning Parsec, so I might have missed something.

**Comment by behrang** [comment]
It doesn't support it out of the box but it has enough combinators to create a parser for indentation. It is currently implemented here: [https://github.com/behrang/YamlSwift/blob/parsec/Yaml/Chapter6.swift#L17](https://github.com/behrang/YamlSwift/blob/parsec/Yaml/Chapter6.swift#L17).

**Comment by seivan** [comment]
Will you be making a package out of it so it works out of the box for YAML? 
It would be nice if I could chose to use OrderedDictionary or OrderedSet for my Dictionaries or Array instead of the Foundation ones.

**Comment by behrang** [comment]
That will be the new implementation of Yaml. 

It won't have OrderedDictionary or OrderedSet as Yaml explicitly specified that mappings should not be ordered.

**Comment by seivan** [comment]
Are you sure it says “won’t be ordered” and not “should not”? 
There is a bit of a semantic difference.

**Comment by behrang** [comment]
> ... These primitives were chosen because they are both powerful and familiar: the sequence corresponds to a Perl array and a Python list, the mapping corresponds to a Perl hash table and a Python dictionary. The scalar represents strings, integers, dates, and other atomic data types.
> 
> ... Thus, while imposing a order on mapping keys is necessary for flattening YAML representations to a sequential access medium, this serialization detail must not be used to convey application level information.
> 
> ... The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique.
> 
> Normally, block sequences and mappings begin on the next line. In some cases, YAML also allows nested block collections to start in-line for a more compact notation. In addition, YAML provides a compact notation for flow mappings with a single key: value pair, nested inside a flow sequence. These allow for a natural “ordered mapping” notation.

**Comment by seivan** [comment]
Thank you, I appreciate your patience with me so far. I guess I need a different way around this issue.

Order matter because I have dependency on previous keys. For now it's solved by using the shorthand so we can get a flow sequence with a natural ordered mapping.
But it's an eyesore with a lot of `-` everywhere. 

It looks even worse in json.

**Comment by behrang** [comment]
You're welcome.
